### ISSUE TITLE
Your dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by k-goncharova** [jdk2pq/washtenaw-covid-tracker#1]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/KW58CA

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by jdk2pq** [comment]
Hi,
Thanks for the notice about this. Sure, I can help out. Beyond continuing to update my dataset on GitHub, is there anything else I need to do?

**Comment by k-goncharova** [comment]
Hi Jake, thank you for your response and willingness to contribute. It would be also helpful, if you could add metadata (description, keywords) to your dataset in Dataverse. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the necessary permissions for editing your dataset .

**Comment by jdk2pq** [comment]
Sounds good. I've made an account on CoronaWhy Dataverse and my username is jkenneally.

**Comment by k-goncharova** [comment]
Thanks, Jake. I've just given you the edit permissions to your dataset. Feel free to contact me, if any help with the update is needed.

**Comment by k-goncharova** [comment]
Hello @jdk2pq , I see that draft version of your dataset with updated metadata a while ago. Just wanted to check if you might need any help with its publishing.

**Comment by jdk2pq** [comment]
Whoops, didn't realize it was a draft. I've submitted it for review. The data will auto-publish from my GitHub repo right? Or is there a way to make that happen?

**Comment by k-goncharova** [comment]
Thank you for your contribution, @jdk2pq! I've just published your updated dataset. Our tech team is setting up auto-push from Github repos, so no extra efforts are required on this. 

Additionally, you may want join our community of 1,000+ contributors in Slack https://www.coronawhy.org/join-the-fight and see if any other initiatives could be interesting to you. We have many cool people and interesting things going on :)
